"use client";

import { useMemo, useRef, useState } from "react";

const EMPTY_PROFILE = { name:"", location:"", contact:"", technicalSkills:"", certifications:[], education:[], roles:[] };
const id = () => `role-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const lines = (v) => String(v || "").split("\n").map(x=>x.trim()).filter(Boolean);
const educationText = (a) => (a||[]).map(e=>[e.degree,e.school].filter(Boolean).join(", ") + (e.dates ? ` (${e.dates})` : "")).filter(Boolean).join("\n");
const card={background:"#fff",border:"1px solid #D8DED9",borderRadius:12,padding:18};
const input={width:"100%",border:"1px solid #CBD4CE",borderRadius:8,padding:"9px 10px",background:"#fff",color:"#17221D"};
const area={...input,resize:"vertical"};
const btn={border:0,borderRadius:8,padding:"10px 14px",fontWeight:700};
const label={display:"block",fontSize:12,fontWeight:700,letterSpacing:".08em",textTransform:"uppercase",color:"#44534C"};

export default function ResumeBuilder(){
 const [profile,setProfile]=useState(EMPTY_PROFILE),[jd,setJd]=useState(""),[tailored,setTailored]=useState(null),[loading,setLoading]=useState(false),[parsing,setParsing]=useState(false),[error,setError]=useState(""),[cvError,setCvError]=useState(""),[edit,setEdit]=useState(false),[paste,setPaste]=useState(false),[pasteText,setPasteText]=useState(""),[fileName,setFileName]=useState(""),[copied,setCopied]=useState(false);
 const fileRef=useRef(null), hasProfile=profile.roles.length>0;
 const score=useMemo(()=>{if(!tailored)return null;const m=tailored.matched_keywords?.length||0,g=tailored.gap_keywords?.length||0;return m+g?Math.round(m/(m+g)*100):null},[tailored]);
 const apply=(p)=>{setProfile({...EMPTY_PROFILE,...p,certifications:p.certifications||[],education:p.education||[],roles:(p.roles||[]).map(r=>({...r,id:r.id||id(),points:r.points||[]}))});setEdit(true)};
 async function parse(form){setParsing(true);setCvError("");try{const r=await fetch("/api/parse-cv",{method:"POST",body:form}),d=await r.json();if(!r.ok)throw Error(d.error||"Could not read the CV.");apply(d.profile)}catch(e){setCvError(e.message)}finally{setParsing(false)}}
 function choose(e){const f=e.target.files?.[0];if(!f)return;setFileName(f.name);const fd=new FormData();fd.append("file",f);parse(fd);e.target.value=""}
 async function generate(){setError("");setTailored(null);if(!jd.trim())return setError("Paste a job description first.");if(!hasProfile)return setError("Upload your CV or add at least one role first.");setLoading(true);try{const r=await fetch("/api/tailor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobDescription:jd,profile})}),d=await r.json();if(!r.ok)throw Error(d.error||"Could not generate the tailored resume.");setTailored(d.tailored)}catch(e){setError(e.message)}finally{setLoading(false)}}
 function role(id_,field,value){setProfile(p=>({...p,roles:p.roles.map(r=>r.id===id_?{...r,[field]:value}:r)}))}
 function copy(){if(!tailored)return;const a=[profile.name||"Your Name",tailored.headline||"",[profile.location,profile.contact].filter(Boolean).join(" · "),"","PROFESSIONAL SUMMARY",tailored.summary||"","","CORE SKILLS",tailored.ordered_skills||"","","EXPERIENCE"];profile.roles.forEach(r=>{const t=tailored.roles?.find(x=>x.id===r.id);a.push(`${r.title} — ${r.company} (${r.dates})`,...(t?.bullets||r.points||[]).map(x=>`• ${x}`),"")});if(profile.certifications.length)a.push("CERTIFICATIONS",...profile.certifications.map(x=>`• ${x}`),"");if(profile.education.length)a.push("EDUCATION",educationText(profile.education));navigator.clipboard.writeText(a.join("\n"));setCopied(true);setTimeout(()=>setCopied(false),1500)}
 return <main style={{maxWidth:1180,margin:"0 auto",padding:"28px 20px 60px"}}><header style={{marginBottom:22}}><div style={{fontSize:11,letterSpacing:".14em",color:"#0B6E5C",textTransform:"uppercase",fontWeight:700}}>Clinical Research Resume Concordance</div><h1 style={{fontFamily:"Fraunces,serif",fontSize:"clamp(28px,4vw,38px)",margin:"6px 0"}}>Upload your CV. Paste a JD. Get a resume built to match it.</h1><p style={{maxWidth:720,color:"#44534C",lineHeight:1.5}}>Built for pharmacovigilance, clinical data management, and clinical SAS/CDM applicants. Unsupported JD requirements are flagged instead of invented.</p></header>
 <div className="rb-grid" style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(0,1.15fr)",gap:20}}><section>
 <div style={card}><label style={label}>Job description</label><textarea rows={12} value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste the full job description here…" style={{...area,marginTop:8}}/><button onClick={generate} disabled={loading} style={{...btn,width:"100%",marginTop:12,background:"#0B6E5C",color:"#fff"}}>{loading?"Matching your profile…":"Generate tailored resume"}</button>{error&&<p style={{color:"#B45309",fontSize:13}}>{error}</p>}</div>
 <div style={{...card,marginTop:16}}><label style={label}>Upload your CV</label><p style={{color:"#68756E",fontSize:13}}>PDF, DOCX, or TXT. The extracted profile is shown for review.</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>fileRef.current?.click()} disabled={parsing} style={{...btn,background:"#fff",color:"#0B6E5C",border:"1px solid #0B6E5C"}}>{parsing?"Reading CV…":"Choose file"}</button><button onClick={()=>setPaste(x=>!x)} disabled={parsing} style={{...btn,background:"#fff",color:"#44534C",border:"1px solid #CBD4CE"}}>{paste?"Hide paste":"Paste text"}</button></div><input ref={fileRef} type="file" accept=".pdf,.docx,.txt" onChange={choose} hidden/>{fileName&&<p style={{fontSize:12}}>File: <strong>{fileName}</strong></p>}{cvError&&<p style={{color:"#B45309",fontSize:13}}>{cvError}</p>}{paste&&<div style={{marginTop:10}}><textarea rows={7} value={pasteText} onChange={e=>setPasteText(e.target.value)} placeholder="Paste your resume text…" style={area}/><button disabled={parsing||!pasteText.trim()} onClick={()=>{const fd=new FormData();fd.append("text",pasteText);parse(fd)}} style={{...btn,marginTop:8,background:"#0B6E5C",color:"#fff",width:"100%"}}>{parsing?"Reading CV…":"Extract profile"}</button></div>}</div>
 <div style={{...card,marginTop:16}}><button onClick={()=>setEdit(x=>!x)} style={{...btn,background:"transparent",padding:0}}>{edit?"▾":"▸"} Your profile facts</button>{edit&&<div style={{marginTop:16,display:"grid",gap:12}}><label style={label}>Name<input style={input} value={profile.name} onChange={e=>setProfile(p=>({...p,name:e.target.value}))}/></label><label style={label}>Location<input style={input} value={profile.location} onChange={e=>setProfile(p=>({...p,location:e.target.value}))}/></label><label style={label}>Contact<input style={input} value={profile.contact} onChange={e=>setProfile(p=>({...p,contact:e.target.value}))}/></label><label style={label}>Technical skills<textarea rows={3} style={area} value={profile.technicalSkills} onChange={e=>setProfile(p=>({...p,technicalSkills:e.target.value}))}/></label><label style={label}>Certifications<textarea rows={3} style={area} value={profile.certifications.join("\n")} onChange={e=>setProfile(p=>({...p,certifications:lines(e.target.value)}))}/></label><label style={label}>Education<textarea rows={3} style={area} value={educationText(profile.education)} onChange={e=>setProfile(p=>({...p,education:lines(e.target.value).map(x=>({degree:x,school:"",dates:""}))}))}/></label><button onClick={()=>setProfile(p=>({...p,roles:[...p.roles,{id:id(),title:"",company:"",dates:"",points:[]}]}))} style={{...btn,background:"#F0F3F1"}}>+ Add role</button>{profile.roles.map(r=><div key={r.id} style={{borderTop:"1px solid #E3E8E4",paddingTop:12}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><input placeholder="Title" style={input} value={r.title} onChange={e=>role(r.id,"title",e.target.value)}/><input placeholder="Company" style={input} value={r.company} onChange={e=>role(r.id,"company",e.target.value)}/><input placeholder="Dates" style={input} value={r.dates} onChange={e=>role(r.id,"dates",e.target.value)}/><button onClick={()=>setProfile(p=>({...p,roles:p.roles.filter(x=>x.id!==r.id)}))} style={{...btn,background:"#FFF4ED",color:"#B45309"}}>Remove</button></div><textarea rows={4} placeholder="One responsibility/achievement per line" style={{...area,marginTop:8}} value={(r.points||[]).join("\n")} onChange={e=>role(r.id,"points",lines(e.target.value))}/></div>)}</div>}</div></section>
 <section>{!tailored?<div style={{...card,minHeight:300,display:"grid",placeItems:"center",color:"#68756E",textAlign:"center"}}>Your tailored resume will appear here after you upload your CV and generate against a job description.</div>:<div style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:12}}><div><div style={{fontSize:12,color:"#68756E"}}>MATCH SCORE</div><strong style={{fontSize:30,color:"#0B6E5C"}}>{score??"—"}%</strong></div><button onClick={copy} style={{...btn,background:"#0B6E5C",color:"#fff"}}>{copied?"Copied":"Copy resume text"}</button></div><h2>{tailored.headline}</h2><p style={{lineHeight:1.6}}>{tailored.summary}</p><h3>Core skills</h3><p>{tailored.ordered_skills}</p><h3>Keyword match</h3><div style={{display:"flex",flexWrap:"wrap",gap:7}}>{(tailored.matched_keywords||[]).map(x=><span key={x} style={{padding:"4px 8px",borderRadius:999,background:"#0B6E5C",color:"#fff",fontSize:12}}>{x}</span>)}</div>{(tailored.gap_keywords||[]).length>0&&<><h3>Gaps to review</h3><div style={{display:"flex",flexWrap:"wrap",gap:7}}>{tailored.gap_keywords.map(x=><span key={x} style={{padding:"4px 8px",borderRadius:999,border:"1px solid #B45309",color:"#B45309",fontSize:12}}>{x}</span>)}</div></>}<h3>Experience</h3>{profile.roles.map(r=>{const t=tailored.roles?.find(x=>x.id===r.id);return <div key={r.id} style={{marginBottom:18}}><strong>{r.title} — {r.company}</strong><div style={{color:"#68756E",fontSize:13}}>{r.dates}</div><ul>{(t?.bullets||r.points||[]).map((b,i)=><li key={i} style={{marginBottom:6}}>{b}</li>)}</ul></div>})}</div>}</section></div></main>
}
